name: Build & Deploy MyHouse24-Rest

on:
  push:
    branches:
      - main


jobs:
  build-deploy:
    name: Build & Deploy MyHouse24-Rest
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Package & Build
        run: |
          mvn clean 
          mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/my-house-24-rest:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/my-house-24-rest:latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy to Server
        run: |
            ssh avada_slj@slj.avada-media-dev1.od.ua "sudo docker pull li4nost/my-house-24-admin:latest"
            ssh avada_slj@slj.avada-media-dev1.od.ua "sudo docker run --name myhouse24-admin -p 9080:8080 -d li4nost/my-house-24-admin:latest"
